version: '3'

services:
  db:
    image: postgres:10.1
    environment:
      - POSTGRES_PASSWORD=root
  web:
    build: .
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
