# Generated by Django 2.0.1 on 2018-02-07 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.Team'),
            preserve_default=False,
        ),
    ]
